# Clean the machine.
- name: 'remove previous docker versions'
  raw: 'sudo apt-get remove docker docker-engine docker.io containerd runc || echo "Forced success"'
# Install docker.
- name: 'Install new docker'
  raw: 'curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh'
# Install docker-compose.
- name: 'Install new docker-compose'
  raw: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
# Add $USER to the docker group.
- name: 'Install new docker-compose'
  raw: 'sudo usermod -aG docker $USER'
- name: 'Set executable permissions on docker-compose.'
  raw: 'sudo chmod +x /usr/local/bin/docker-compose'